name: drillx-contracts
plugins:
  - name: vyper
  - name: hardhat

default_ecosystem: ethereum
ethereum:
  default_network: local
  local:
    default_provider: hardhat
    
hardhat:
  port: 8545
  host: http://127.0.0.1
  accounts:
    - private_key: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
      balance: "100 ether"
    - private_key: "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
      balance: "100 ether"